export default {
  'simple-chart': {
    code:
      "/**\n * Assuming you have installed fusioncharts using npm\n * Following code snippet can be used\n*/\nvar FusionCharts = require('fusioncharts');\nvar Charts = require('fusioncharts/fusioncharts.charts');\nvar FusionTheme = require('fusioncharts/themes/fusioncharts.theme.fusion');\nvar $ = require('jquery');\nvar jQueryFusionCharts = require('jquery-fusioncharts');\n\nCharts(FusionCharts); // Resolve Charts as dependency for FusionCharts.\nFusionTheme(FusionCharts);  // Resolve Fusion theme as dependency for FusionCharts\njQueryFusionCharts(FusionCharts); // Resolve FusionCharts as dependency for jqueryFusionCharts\n\n$('document').ready(function () {\n  $('#chart-container').insertFusionCharts({\n    type: 'column2d',\n    width: '600',\n    height: '400',\n    dataFormat: 'json',\n    dataSource:  { /* see data tab */ }    \n  });\n});\n\n/* \nNOTE: \n  * In case you downloaded fusioncharts in zipped format\n  * var FusionCharts = require('/path/to/fusioncharts/fusioncharts.js');\n  * var Charts = require('/path/to/fusioncharts/fusioncharts.charts.js');\n  * var FusionTheme = require('/path/to/fusioncharts/fusioncharts.theme.fusion.js');\n*/",
    html:
      '<div id="chart-container">\n    FusionCharts will render here\n</div>',
    data:
      '{\n    "chart": {\n        "caption": "Countries With Most Oil Reserves [2017-18]",\n        "subCaption": "In MMbbl = One Million barrels",\n        "xAxisName": "Country",\n        "yAxisName": "Reserves (MMbbl)",\n        "numberSuffix": "K",\n        "theme": "fusion"\n    },\n    "data": [\n        {\n            "label": "Venezuela",\n            "value": "290"\n        },\n        {\n            "label": "Saudi",\n            "value": "260"\n        },\n        {\n            "label": "Canada",\n            "value": "180"\n        },\n        {\n            "label": "Iran",\n            "value": "140"\n        },\n        {\n            "label": "Russia",\n            "value": "115"\n        },\n        {\n            "label": "UAE",\n            "value": "100"\n        },\n        {\n            "label": "US",\n            "value": "30"\n        },\n        {\n            "label": "China",\n            "value": "30"\n        }\n    ]\n}'
  }
};
